name: vault_ospf_intermediario

topology:
  defaults:
    kind: ceos
    startup-config: configs/arista/__clabNodeName__.cfg

  nodes:
    r1:
      mgmt-ipv4: 172.20.20.11
      kind: ceos
      image: ghcr.io/autonetops/ceos:latest
    r2:
      mgmt-ipv4: 172.20.20.12
      kind: ceos
      image: ghcr.io/autonetops/ceos:latest
    r3:
      mgmt-ipv4: 172.20.20.13
      kind: ceos
      image: ghcr.io/autonetops/ceos:latest
    r4:
      mgmt-ipv4: 172.20.20.14
      kind: ceos
      image: ghcr.io/autonetops/ceos:latest
  
  links:
    - endpoints: ["r1:eth1", "r2:eth1"]
    - endpoints: ["r2:eth2", "r3:eth2"]
    - endpoints: ["r3:eth1", "r4:eth1"]
    - endpoints: ["r1:eth2", "r4:eth2"]