- ip: 172.20.20.11
  name: r1
  type: arista_eos
  username: admin
  password: autonetops
- ip: 172.20.20.12
  name: r2
  type: arista_eos
  username: admin
  password: autonetops
- ip: 172.20.20.13
  name: r3
  type: arista_eos
  username: admin
  password: autonetops
- ip: 172.20.20.13
  name: r4
  type: arista_eos
  username: admin
  password: autonetops